<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Quali_ProWEB_23-SVN"
           tests="5"
           failures="2"
           errors="0"
           skipped="3"
           time="-3241279520,489">
    <properties></properties>

            <testcase
                name="setUpClass"
                time="0,050"
                classname="com.qualiprobdd.e2etests.EmpRunner">

            <failure type="java.lang.NoSuchMethodError" message="cucumber.runtime.RuntimeOptions.reporter(Ljava/lang/ClassLoader;)Lgherkin/formatter/Reporter;">
                <![CDATA[java.lang.NoSuchMethodError: cucumber.runtime.RuntimeOptions.reporter(Ljava/lang/ClassLoader;)Lgherkin/formatter/Reporter;
                cucumber.api.testng.TestNGCucumberRunner.<init>(TestNGCucumberRunner.java:41)cucumber.api.testng.AbstractTestNGCucumberTests.setUpClass(AbstractTestNGCucumberTests.java:16)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)java.util.ArrayList.forEach(ArrayList.java:1259)org.testng.TestRunner.privateRun(TestRunner.java:764)org.testng.TestRunner.run(TestRunner.java:585)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)org.testng.TestNG.runSuitesLocally(TestNG.java:1140)org.testng.TestNG.runSuites(TestNG.java:1069)org.testng.TestNG.run(TestNG.java:1037)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>
            <testcase
                name="tearDownClass"
                time="0,001"
                classname="com.qualiprobdd.e2etests.EmpRunner">

            <failure type="java.lang.NullPointerException" message="(null)">
                <![CDATA[java.lang.NullPointerException
                cucumber.api.testng.AbstractTestNGCucumberTests.tearDownClass(AbstractTestNGCucumberTests.java:34)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)java.util.ArrayList.forEach(ArrayList.java:1259)org.testng.TestRunner.privateRun(TestRunner.java:764)org.testng.TestRunner.run(TestRunner.java:585)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)org.testng.TestNG.runSuitesLocally(TestNG.java:1140)org.testng.TestNG.runSuites(TestNG.java:1069)org.testng.TestNG.run(TestNG.java:1037)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>

            <testcase
                name="setup"
                time="0.0"
                classname="com.qualiprobdd.e2etests.EmpRunner">
            </testcase>
            <testcase
                name="writeExtentReport"
                time="0.0"
                classname="com.qualiprobdd.e2etests.EmpRunner">
            </testcase>
            <testcase
                name="feature"
                time="0.0"
                classname="com.qualiprobdd.e2etests.EmpRunner">
            </testcase>

</testsuite>
